import java.io.ByteArrayOutputStream
import org.gradle.api.publish.maven.MavenPublication
import org.gradle.api.tasks.bundling.Jar
import org.jetbrains.kotlin.gradle.dsl.abi.ExperimentalAbiValidation
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `java-library`
    `maven-publish`
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.dokka")
}

val kotlinModuleName = "io.github.ulviar.procwright.kotlin"
val kotlinNullnessCompiler = configurations.create("kotlinNullnessCompiler")

dependencies {
    api(project(":"))
    api("org.jetbrains.kotlin:kotlin-stdlib:2.4.20")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")

    testImplementation(kotlin("test"))
    kotlinNullnessCompiler("org.jetbrains.kotlin:kotlin-compiler-embeddable:2.4.20")
}

java {
    modularity.inferModulePath.set(true)
    withSourcesJar()
}

val compileKotlin = tasks.named<KotlinCompile>("compileKotlin")

tasks.named<JavaCompile>("compileJava") {
    dependsOn(compileKotlin)
    options.compilerArgs.addAll(
        listOf(
            "--patch-module",
            "$kotlinModuleName=${compileKotlin.flatMap { it.destinationDirectory }.get().asFile.absolutePath}",
        )
    )
}

val dokkaHtmlOutput = layout.buildDirectory.dir("kdoc-validation")
val kotlinJavadocJar =
    tasks.register<Jar>("javadocJar") {
        description = "Assembles the Kotlin API reference generated by Dokka."
        group = LifecycleBasePlugin.BUILD_GROUP
        archiveClassifier.set("javadoc")
        dependsOn(tasks.named("dokkaGeneratePublicationHtml"))
        from(dokkaHtmlOutput)
        isPreserveFileTimestamps = false
        isReproducibleFileOrder = true
    }

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            artifact(kotlinJavadocJar)
            artifactId = "procwright-kotlin"
            pom {
                name.set("Procwright Kotlin")
                description.set("Optional Kotlin ergonomics for Procwright scenario workflows.")
            }
        }
    }
}

@OptIn(ExperimentalAbiValidation::class)
kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xjspecify-annotations=strict")
    }
    abiValidation()
}

dokka {
    dokkaPublications.html {
        outputDirectory.set(dokkaHtmlOutput)
        failOnWarning.set(true)
        offlineMode.set(true)
    }
    dokkaSourceSets.configureEach {
        reportUndocumented.set(true)
        jdkVersion.set(25)
        includes.from(layout.projectDirectory.file("src/main/kotlin-api.md"))
        externalDocumentationLinks.register("procwright-core") {
            url("https://ulviar.github.io/Procwright/api/java/core/")
            packageListUrl(
                rootProject.layout.buildDirectory
                    .file("docs/javadoc/element-list")
                    .get()
                    .asFile
                    .toURI()
                    .toString()
            )
        }
    }
}

tasks.named("dokkaGeneratePublicationHtml") {
    dependsOn(rootProject.tasks.named("javadoc"))
    inputs.file(rootProject.layout.buildDirectory.file("docs/javadoc/element-list"))
}

val kotlinNullnessFixtureClasspath =
    sourceSets.main.get().output + configurations.compileClasspath.get()

tasks.register<JavaExec>("kotlinJSpecifyStrictnessCheck") {
    description = "Proves that Kotlin consumers reject null at a strict JSpecify boundary."
    group = LifecycleBasePlugin.VERIFICATION_GROUP
    dependsOn(tasks.named("classes"))

    val sourceFile = layout.projectDirectory.file("src/nullnessFixtures/kotlin/CommandNull.kt")
    val outputDirectory = layout.buildDirectory.dir("jspecify-strictness")
    val diagnostics = ByteArrayOutputStream()
    inputs.file(sourceFile)
    inputs.files(kotlinNullnessFixtureClasspath)
    outputs.dir(outputDirectory)
    classpath = kotlinNullnessCompiler
    mainClass.set("org.jetbrains.kotlin.cli.jvm.K2JVMCompiler")
    isIgnoreExitValue = true
    standardOutput = diagnostics
    errorOutput = diagnostics
    argumentProviders.add(
        CommandLineArgumentProvider {
            listOf(
                "-jvm-target",
                "25",
                "-no-stdlib",
                "-no-reflect",
                "-Xjspecify-annotations=strict",
                "-classpath",
                kotlinNullnessFixtureClasspath.filter(File::exists).asPath,
                "-d",
                outputDirectory.get().asFile.absolutePath,
                sourceFile.asFile.absolutePath,
            )
        }
    )
    doFirst {
        diagnostics.reset()
        delete(outputDirectory)
    }
    doLast {
        val output = diagnostics.toString(Charsets.UTF_8)
        if (executionResult.get().exitValue == 0) {
            throw GradleException("Strict JSpecify fixture compiled successfully")
        }
        if (!output.contains("non-null type 'String'", ignoreCase = true)) {
            throw GradleException(
                "Strict JSpecify fixture failed for an unexpected reason:\n$output"
            )
        }
    }
}

tasks.check {
    dependsOn(kotlinJavadocJar)
}
