/* SPDX-License-Identifier: Apache-2.0 */

package io.github.ulviar.procwright.kotlin

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.util.TreeSet
import kotlin.ExperimentalContextParameters
import kotlin.Metadata
import kotlin.metadata.ExperimentalContextReceivers
import kotlin.metadata.KmClass
import kotlin.metadata.KmClassifier
import kotlin.metadata.KmConstructor
import kotlin.metadata.KmDeclarationContainer
import kotlin.metadata.KmFlexibleTypeUpperBound
import kotlin.metadata.KmFunction
import kotlin.metadata.KmPackage
import kotlin.metadata.KmProperty
import kotlin.metadata.KmPropertyAccessorAttributes
import kotlin.metadata.KmType
import kotlin.metadata.KmTypeAlias
import kotlin.metadata.KmTypeParameter
import kotlin.metadata.KmTypeProjection
import kotlin.metadata.KmValueParameter
import kotlin.metadata.KmVariance
import kotlin.metadata.Visibility
import kotlin.metadata.isDefinitelyNonNull
import kotlin.metadata.isNullable
import kotlin.metadata.jvm.JvmMethodSignature
import kotlin.metadata.jvm.KotlinClassMetadata
import kotlin.metadata.jvm.getterSignature
import kotlin.metadata.jvm.signature
import kotlin.metadata.visibility
import org.junit.jupiter.api.Test

@OptIn(ExperimentalContextParameters::class, ExperimentalContextReceivers::class)
@Suppress("DEPRECATION_ERROR")
internal object KotlinSourceNullabilityCompatibility {

    private const val API_PACKAGE = "io.github.ulviar.procwright.kotlin"
    private const val HEADER =
        "# Generated by ./gradlew :procwright-kotlin:writeKotlinSourceNullabilityBaseline"

    @JvmStatic
    fun main(args: Array<String>) {
        require(args.size == 2) {
            "Usage: KotlinSourceNullabilityCompatibility <check|write> <baseline>"
        }
        selfTest()
        val baseline = Path.of(args[1])
        val snapshot = publicApiSnapshot()
        when (args[0]) {
            "check" -> verifyBaseline(baseline, snapshot)
            "write" -> writeBaseline(baseline, snapshot)
            else -> error("Unknown mode: ${args[0]}")
        }
    }

    fun publicApiSnapshot(): Set<String> {
        val classesRoot =
            Path.of(
                ProtocolAdapterFactoryDsl::class.java.protectionDomain.codeSource.location.toURI()
            )
        val classes =
            Files.walk(classesRoot).use { paths ->
                paths
                    .filter(Files::isRegularFile)
                    .filter { it.fileName.toString().endsWith(".class") }
                    .filter { it.fileName.toString() != "module-info.class" }
                    .map { classFile -> className(classesRoot, classFile) }
                    .filter { it.startsWith("$API_PACKAGE.") }
                    .map {
                        Class.forName(it, false, ProtocolAdapterFactoryDsl::class.java.classLoader)
                    }
                    .filter { it.getAnnotation(Metadata::class.java) != null }
                    .toList()
            }
        return snapshot(classes)
    }

    fun selfTest() {
        verifyNullabilityMutation()
        verifyParameterNameMutations()
        verifyCompiledPublicConstructs()
        verifyMultifileMetadataBranches()
        verifyPropertyAndTypeAliasTraversalMutations()
        verifySyntheticTypeBranches()
        verifySyntheticContextAndAccessorBranches()
    }

    private fun verifyNullabilityMutation() {
        val approvedClass =
            Class.forName(
                "io.github.ulviar.procwright.kotlin.nullability.approved.ApiKt",
                false,
                KotlinSourceNullabilityCompatibility::class.java.classLoader,
            )
        val hostileClass =
            Class.forName(
                "io.github.ulviar.procwright.kotlin.nullability.hostile.ApiKt",
                false,
                KotlinSourceNullabilityCompatibility::class.java.classLoader,
            )
        val approved = normalizedFixtureSnapshot(approvedClass, "approved")
        val hostile = normalizedFixtureSnapshot(hostileClass, "hostile")
        val diff = compatibilityDiff(approved, hostile)
        val expectedChangedPositions =
            setOf(
                "typeParameter[T].bound[0]",
                "receiver",
                "receiver.typeArgument[0]",
                "receiver.typeArgument[1]",
                "receiver.typeArgument[1].typeArgument[0]",
                "parameter[0]",
                "parameter[0].typeArgument[0]",
                "parameter[0].typeArgument[1]",
                "parameter[0].typeArgument[1].typeArgument[0]",
                "return",
                "return.typeArgument[0]",
                "return.typeArgument[1]",
                "return.typeArgument[1].typeArgument[0]",
            )

        check(diff.removedOrChanged.map(::position).toSet() == expectedChangedPositions) {
            "Hostile fixture removed unexpected nullability positions: ${diff.removedOrChanged}"
        }
        check(diff.added.map(::position).toSet() == expectedChangedPositions) {
            "Hostile fixture added unexpected nullability positions: ${diff.added}"
        }
        check(diff.removedOrChanged.all { it.contains("\tNON_NULL\t") }) {
            "Approved fixture must be non-null at every changed position: ${diff.removedOrChanged}"
        }
        check(diff.added.all { it.contains("\tNULLABLE\t") }) {
            "Hostile fixture must weaken every changed position to nullable: ${diff.added}"
        }
    }

    private fun verifyParameterNameMutations() {
        val approved =
            normalizedFixtureSnapshot(
                fixtureClasses("approved", "ApiKt", "SurfaceKt", "ConstructorAndPropertyFixture"),
                "approved",
            )
        val renamed =
            normalizedFixtureSnapshot(
                fixtureClasses("renamed", "ApiKt", "SurfaceKt", "ConstructorAndPropertyFixture"),
                "renamed",
            )
        val diff = compatibilityDiff(approved, renamed)
        val removedNames =
            diff.removedOrChanged.filter(::isParameterNameSignature).map(::parameterNameKey).toSet()
        val addedNames =
            diff.added.filter(::isParameterNameSignature).map(::parameterNameKey).toSet()
        val expectedRemoved =
            setOf(
                "CONSTRUCTOR fixture.ConstructorAndPropertyFixture#<init>|parameter[0]|initial",
                "FUNCTION fixture.ApiKt#transform|parameter[0]|input",
                "FUNCTION fixture.ConstructorAndPropertyFixture#varargValues|parameter[0]|items",
                "FUNCTION fixture.SurfaceKt#definitelyNonNull|parameter[0]|value",
                "FUNCTION fixture.SurfaceKt#ownerAndAlias|parameter[0]|value",
                "FUNCTION fixture.SurfaceKt#starProjection|parameter[0]|values",
                "PROPERTY fixture.ConstructorAndPropertyFixture#getValue|setterParameter|incoming",
            )
        val expectedAdded =
            setOf(
                "CONSTRUCTOR fixture.ConstructorAndPropertyFixture#<init>|parameter[0]|renamedInitial",
                "FUNCTION fixture.ApiKt#transform|parameter[0]|renamedInput",
                "FUNCTION fixture.ConstructorAndPropertyFixture#varargValues|parameter[0]|renamedItems",
                "FUNCTION fixture.SurfaceKt#definitelyNonNull|parameter[0]|renamedValue",
                "FUNCTION fixture.SurfaceKt#ownerAndAlias|parameter[0]|renamedValue",
                "FUNCTION fixture.SurfaceKt#starProjection|parameter[0]|renamedValues",
                "PROPERTY fixture.ConstructorAndPropertyFixture#getValue|setterParameter|renamedIncoming",
            )

        check(removedNames == expectedRemoved) {
            "Parameter-name fixture removed unexpected signatures: $removedNames"
        }
        check(addedNames == expectedAdded) {
            "Parameter-name fixture added unexpected signatures: $addedNames"
        }
        check(
            diff.removedOrChanged.all(::isParameterNameSignature) &&
                diff.added.all(::isParameterNameSignature)
        ) {
            "Parameter-name fixtures must differ only in KmValueParameter.name: $diff"
        }
    }

    private fun verifyCompiledPublicConstructs() {
        val snapshot =
            normalizedFixtureSnapshot(
                fixtureClasses(
                    "approved",
                    "SurfaceKt",
                    "ConstructorAndPropertyFixture",
                    "GenericOuter",
                    "GenericOuter\$Inner",
                ),
                "approved",
            )

        assertContains(snapshot, "CONSTRUCTOR fixture.ConstructorAndPropertyFixture#<init>")
        assertContains(snapshot, "PROPERTY fixture.ConstructorAndPropertyFixture#getValue")
        assertContains(snapshot, "TYPE_ALIAS fixture.SurfaceKt#NestedAlias")
        assertContains(snapshot, "\tparameter[0].varargElement\t")
        assertContains(snapshot, "\tSTAR")
        assertContains(snapshot, "\tDEFINITELY_NON_NULL\tTYPE_PARAMETER:T")
        assertContains(snapshot, "\treceiver.owner\t")
        assertContains(snapshot, ".abbreviated\t")
    }

    private fun verifySyntheticTypeBranches() {
        // Kotlin source cannot explicitly spell a flexible platform type. Constructing the
        // supported metadata node makes its lower/upper nullness traversal deterministic.
        val typeParameter = KmTypeParameter("T", 7, KmVariance.INVARIANT)
        val definitelyNonNull =
            kmType(KmClassifier.TypeParameter(typeParameter.id)).apply {
                isDefinitelyNonNull = true
            }
        val root =
            kmType(KmClassifier.Class("fixture/Inner")).apply {
                arguments += KmTypeProjection.STAR
                arguments += KmTypeProjection(KmVariance.INVARIANT, definitelyNonNull)
                outerType = nullableType(KmClassifier.Class("fixture/Outer"))
                abbreviatedType = kmType(KmClassifier.TypeAlias("fixture/Alias"))
                flexibleTypeUpperBound =
                    KmFlexibleTypeUpperBound(
                        nullableType(KmClassifier.Class("kotlin/Any")),
                        "kotlin.jvm.PlatformType",
                    )
            }
        val declaration = "FUNCTION fixture.Branches#types()Ljava/lang/Object;"
        val actual = buildSet { addType(declaration, "return", root, mapOf(7 to typeParameter)) }
        val expected =
            setOf(
                "KOTLIN_TYPE\t$declaration\treturn\tNON_NULL\tCLASS:fixture.Inner",
                "KOTLIN_PROJECTION\t$declaration\treturn.typeArgument[0]\tSTAR",
                "KOTLIN_PROJECTION\t$declaration\treturn.typeArgument[1]\tINVARIANT",
                "KOTLIN_TYPE\t$declaration\treturn.typeArgument[1]\tDEFINITELY_NON_NULL\tTYPE_PARAMETER:T",
                "KOTLIN_TYPE\t$declaration\treturn.owner\tNULLABLE\tCLASS:fixture.Outer",
                "KOTLIN_TYPE\t$declaration\treturn.abbreviated\tNON_NULL\tTYPE_ALIAS:fixture.Alias",
                "KOTLIN_FLEXIBILITY\t$declaration\treturn\tkotlin.jvm.PlatformType",
                "KOTLIN_TYPE\t$declaration\treturn.flexibleUpperBound\tNULLABLE\tCLASS:kotlin.Any",
            )

        check(actual == expected) {
            "Synthetic type branches changed: expected $expected, got $actual"
        }
    }

    private fun verifyPropertyAndTypeAliasTraversalMutations() {
        val propertyOwner = "fixture.PropertyApi"
        val approvedProperty = buildSet {
            addProperty(propertyOwner, propertyTraversalFixture(), emptyMap())
        }
        assertOnlyNullabilityMutation(
            approvedProperty,
            buildSet {
                addProperty(
                    propertyOwner,
                    propertyTraversalFixture(nullableBound = true),
                    emptyMap(),
                )
            },
            "typeParameter[T].bound[0]",
        )
        assertOnlyNullabilityMutation(
            approvedProperty,
            buildSet {
                addProperty(
                    propertyOwner,
                    propertyTraversalFixture(nullableReceiver = true),
                    emptyMap(),
                )
            },
            "receiver",
        )

        val aliasOwner = "fixture.AliasApi"
        val approvedAlias = buildSet {
            addTypeAlias(aliasOwner, typeAliasTraversalFixture(), emptyMap())
        }
        assertOnlyNullabilityMutation(
            approvedAlias,
            buildSet {
                addTypeAlias(
                    aliasOwner,
                    typeAliasTraversalFixture(nullableUnderlying = true),
                    emptyMap(),
                )
            },
            "underlying",
        )
        assertOnlyNullabilityMutation(
            approvedAlias,
            buildSet {
                addTypeAlias(
                    aliasOwner,
                    typeAliasTraversalFixture(nullableExpanded = true),
                    emptyMap(),
                )
            },
            "expanded",
        )
    }

    private fun propertyTraversalFixture(
        nullableBound: Boolean = false,
        nullableReceiver: Boolean = false,
    ): KmProperty {
        val typeParameter = KmTypeParameter("T", 31, KmVariance.INVARIANT)
        typeParameter.upperBounds +=
            if (nullableBound) nullableType(KmClassifier.Class("kotlin/String"))
            else kmType(KmClassifier.Class("kotlin/String"))
        val typeParameterType = kmType(KmClassifier.TypeParameter(typeParameter.id))
        val receiver =
            kmType(KmClassifier.Class("kotlin/collections/List")).apply {
                arguments += KmTypeProjection(KmVariance.INVARIANT, typeParameterType)
                isNullable = nullableReceiver
            }
        return KmProperty("mapped").apply {
            visibility = Visibility.PUBLIC
            getterSignature =
                JvmMethodSignature("getMapped", "(Ljava/util/List;)Ljava/lang/Object;")
            typeParameters += typeParameter
            receiverParameterType = receiver
            returnType = typeParameterType
        }
    }

    private fun typeAliasTraversalFixture(
        nullableUnderlying: Boolean = false,
        nullableExpanded: Boolean = false,
    ): KmTypeAlias =
        KmTypeAlias("Alias").apply {
            visibility = Visibility.PUBLIC
            underlyingType =
                kmType(KmClassifier.Class("kotlin/collections/List")).apply {
                    isNullable = nullableUnderlying
                }
            expandedType =
                kmType(KmClassifier.Class("kotlin/collections/Collection")).apply {
                    isNullable = nullableExpanded
                }
        }

    private fun assertOnlyNullabilityMutation(
        approved: Set<String>,
        hostile: Set<String>,
        expectedPosition: String,
    ) {
        val diff = compatibilityDiff(approved, hostile)
        check(
            diff.removedOrChanged.size == 1 &&
                position(diff.removedOrChanged.single()) == expectedPosition &&
                diff.removedOrChanged.single().contains("\tNON_NULL\t")
        ) {
            "Approved metadata did not expose exactly '$expectedPosition': $diff"
        }
        check(
            diff.added.size == 1 &&
                position(diff.added.single()) == expectedPosition &&
                diff.added.single().contains("\tNULLABLE\t")
        ) {
            "Hostile metadata did not mutate exactly '$expectedPosition': $diff"
        }
    }

    private fun verifySyntheticContextAndAccessorBranches() {
        // Current Kotlin source cannot emit legacy context receivers and named context
        // parameters on one declaration, while the supported metadata model exposes both.
        val stringType = kmType(KmClassifier.Class("kotlin/String"))
        val function =
            KmFunction("contextual").apply {
                visibility = Visibility.PUBLIC
                signature =
                    JvmMethodSignature("contextual", "(Ljava/lang/String;)Ljava/lang/String;")
                contextReceiverTypes += stringType
                contextParameters += valueParameter("scope", stringType)
                valueParameters += valueParameter("input", stringType)
                returnType = stringType
            }
        val property =
            KmProperty("value").apply {
                visibility = Visibility.PUBLIC
                getterSignature = JvmMethodSignature("getValue", "()Ljava/lang/String;")
                contextReceiverTypes += stringType
                contextParameters += valueParameter("propertyScope", stringType)
                returnType = stringType
                setter = KmPropertyAccessorAttributes().apply { visibility = Visibility.PUBLIC }
                setterParameter = valueParameter("incoming", stringType)
            }
        val actual = buildSet {
            addFunction("fixture.ContextApi", function, emptyMap())
            addProperty("fixture.ContextApi", property, emptyMap())
        }
        val functionDeclaration =
            "FUNCTION fixture.ContextApi#contextual(Ljava/lang/String;)Ljava/lang/String;"
        val propertyDeclaration = "PROPERTY fixture.ContextApi#getValue()Ljava/lang/String;"
        val expected =
            setOf(
                "KOTLIN_TYPE\t$functionDeclaration\tcontextReceiver[0]\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_PARAMETER_NAME\t$functionDeclaration\tcontextParameter[0]\tscope",
                "KOTLIN_TYPE\t$functionDeclaration\tcontextParameter[0]\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_PARAMETER_NAME\t$functionDeclaration\tparameter[0]\tinput",
                "KOTLIN_TYPE\t$functionDeclaration\tparameter[0]\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_TYPE\t$functionDeclaration\treturn\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_TYPE\t$propertyDeclaration\tcontextReceiver[0]\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_PARAMETER_NAME\t$propertyDeclaration\tcontextParameter[0]\tpropertyScope",
                "KOTLIN_TYPE\t$propertyDeclaration\tcontextParameter[0]\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_TYPE\t$propertyDeclaration\treturn\tNON_NULL\tCLASS:kotlin.String",
                "KOTLIN_PARAMETER_NAME\t$propertyDeclaration\tsetterParameter\tincoming",
                "KOTLIN_TYPE\t$propertyDeclaration\tsetterParameter\tNON_NULL\tCLASS:kotlin.String",
            )

        check(actual == expected) {
            "Synthetic context/accessor branches changed: expected $expected, got $actual"
        }
    }

    private fun verifyMultifileMetadataBranches() {
        val facade = fixtureClasses("approved", "MultifileApi").single()
        val firstPart = fixtureClasses("approved", "MultifileApi__MultifileFirstKt").single()
        val secondPart = fixtureClasses("approved", "MultifileApi__MultifileSecondKt").single()
        check(
            KotlinClassMetadata.readStrict(facade.getAnnotation(Metadata::class.java))
                is KotlinClassMetadata.MultiFileClassFacade
        ) {
            "Compiled multifile facade did not produce MultiFileClassFacade metadata"
        }
        check(
            KotlinClassMetadata.readStrict(firstPart.getAnnotation(Metadata::class.java))
                is KotlinClassMetadata.MultiFileClassPart
        ) {
            "Compiled multifile part did not produce MultiFileClassPart metadata"
        }

        val snapshot = normalizedFixtureSnapshot(listOf(facade, firstPart, secondPart), "approved")
        assertContains(snapshot, "FUNCTION fixture.MultifileApi__MultifileFirstKt#multifileFirst")
        assertContains(snapshot, "FUNCTION fixture.MultifileApi__MultifileSecondKt#multifileSecond")
    }

    private fun snapshot(classes: Collection<Class<*>>): Set<String> = buildSet {
        classes.sortedBy(Class<*>::getName).forEach { type ->
            val metadata = KotlinClassMetadata.readStrict(type.getAnnotation(Metadata::class.java))
            when (metadata) {
                is KotlinClassMetadata.Class ->
                    if (isEffectivelyPublicKotlinClass(type)) {
                        addClass(type.name, metadata.kmClass)
                    }
                is KotlinClassMetadata.FileFacade -> addPackage(type.name, metadata.kmPackage)
                is KotlinClassMetadata.MultiFileClassPart ->
                    addPackage(type.name, metadata.kmPackage)
                // These metadata kinds have no declaration container, so no supported public
                // receiver, parameter, return, bound, property, constructor, or alias is hidden.
                is KotlinClassMetadata.MultiFileClassFacade,
                is KotlinClassMetadata.SyntheticClass,
                is KotlinClassMetadata.Unknown -> Unit
            }
        }
    }

    private fun MutableSet<String>.addClass(owner: String, declaration: KmClass) {
        val classTypeParameters = declaration.typeParameters.associateBy(KmTypeParameter::id)
        addTypeParameters("CLASS $owner", declaration.typeParameters, classTypeParameters)
        declaration.supertypes.forEachIndexed { index, type ->
            addType("CLASS $owner", "supertype[$index]", type, classTypeParameters)
        }
        addContainer(owner, declaration, classTypeParameters)
        declaration.constructors
            .filter { it.visibility.isApiVisibility() }
            .forEach { constructor -> addConstructor(owner, constructor, classTypeParameters) }
    }

    private fun MutableSet<String>.addPackage(owner: String, declaration: KmPackage) {
        addContainer(owner, declaration, emptyMap())
    }

    private fun MutableSet<String>.addContainer(
        owner: String,
        declaration: KmDeclarationContainer,
        parentTypeParameters: Map<Int, KmTypeParameter>,
    ) {
        declaration.functions
            .filter { it.visibility.isApiVisibility() }
            .forEach { function -> addFunction(owner, function, parentTypeParameters) }
        declaration.properties
            .filter { it.visibility.isApiVisibility() }
            .forEach { property -> addProperty(owner, property, parentTypeParameters) }
        declaration.typeAliases
            .filter { it.visibility.isApiVisibility() }
            .forEach { alias -> addTypeAlias(owner, alias, parentTypeParameters) }
    }

    private fun MutableSet<String>.addFunction(
        owner: String,
        function: KmFunction,
        parentTypeParameters: Map<Int, KmTypeParameter>,
    ) {
        val signature =
            checkNotNull(function.signature) {
                "Public Kotlin function has no JVM signature: $owner#${function.name}"
            }
        val declaration = "FUNCTION $owner#${signature.name}${signature.descriptor}"
        val typeParameters =
            parentTypeParameters + function.typeParameters.associateBy(KmTypeParameter::id)
        addTypeParameters(declaration, function.typeParameters, typeParameters)
        function.receiverParameterType?.let { addType(declaration, "receiver", it, typeParameters) }
        function.contextReceiverTypes.forEachIndexed { index, type ->
            addType(declaration, "contextReceiver[$index]", type, typeParameters)
        }
        function.contextParameters.forEachIndexed { index, parameter ->
            addValueParameter(declaration, "contextParameter[$index]", parameter, typeParameters)
        }
        function.valueParameters.forEachIndexed { index, parameter ->
            addValueParameter(declaration, "parameter[$index]", parameter, typeParameters)
        }
        addType(declaration, "return", function.returnType, typeParameters)
    }

    private fun MutableSet<String>.addConstructor(
        owner: String,
        constructor: KmConstructor,
        typeParameters: Map<Int, KmTypeParameter>,
    ) {
        val signature =
            checkNotNull(constructor.signature) {
                "Public Kotlin constructor has no JVM signature: $owner"
            }
        val declaration = "CONSTRUCTOR $owner#${signature.name}${signature.descriptor}"
        constructor.valueParameters.forEachIndexed { index, parameter ->
            addValueParameter(declaration, "parameter[$index]", parameter, typeParameters)
        }
    }

    private fun MutableSet<String>.addProperty(
        owner: String,
        property: KmProperty,
        parentTypeParameters: Map<Int, KmTypeParameter>,
    ) {
        val signature = property.getterSignature
        val declaration =
            "PROPERTY $owner#${signature?.name ?: property.name}${signature?.descriptor ?: ""}"
        val typeParameters =
            parentTypeParameters + property.typeParameters.associateBy(KmTypeParameter::id)
        addTypeParameters(declaration, property.typeParameters, typeParameters)
        property.receiverParameterType?.let { addType(declaration, "receiver", it, typeParameters) }
        property.contextReceiverTypes.forEachIndexed { index, type ->
            addType(declaration, "contextReceiver[$index]", type, typeParameters)
        }
        property.contextParameters.forEachIndexed { index, parameter ->
            addValueParameter(declaration, "contextParameter[$index]", parameter, typeParameters)
        }
        addType(declaration, "return", property.returnType, typeParameters)
        if (property.setter?.visibility?.isApiVisibility() == true) {
            property.setterParameter?.let {
                addValueParameter(declaration, "setterParameter", it, typeParameters)
            }
        }
    }

    private fun MutableSet<String>.addValueParameter(
        declaration: String,
        position: String,
        parameter: KmValueParameter,
        typeParameters: Map<Int, KmTypeParameter>,
    ) {
        add("KOTLIN_PARAMETER_NAME\t$declaration\t$position\t${parameter.name}")
        addType(declaration, position, parameter.type, typeParameters)
        parameter.varargElementType?.let {
            addType(declaration, "$position.varargElement", it, typeParameters)
        }
    }

    private fun MutableSet<String>.addTypeAlias(
        owner: String,
        alias: KmTypeAlias,
        parentTypeParameters: Map<Int, KmTypeParameter>,
    ) {
        val declaration = "TYPE_ALIAS $owner#${alias.name}"
        val typeParameters =
            parentTypeParameters + alias.typeParameters.associateBy(KmTypeParameter::id)
        addTypeParameters(declaration, alias.typeParameters, typeParameters)
        addType(declaration, "underlying", alias.underlyingType, typeParameters)
        addType(declaration, "expanded", alias.expandedType, typeParameters)
    }

    private fun MutableSet<String>.addTypeParameters(
        declaration: String,
        parameters: List<KmTypeParameter>,
        typeParameters: Map<Int, KmTypeParameter>,
    ) {
        parameters.forEach { parameter ->
            parameter.upperBounds.forEachIndexed { index, bound ->
                addType(
                    declaration,
                    "typeParameter[${parameter.name}].bound[$index]",
                    bound,
                    typeParameters,
                )
            }
        }
    }

    private fun MutableSet<String>.addType(
        declaration: String,
        position: String,
        type: KmType,
        typeParameters: Map<Int, KmTypeParameter>,
    ) {
        add(
            listOf(
                    "KOTLIN_TYPE",
                    declaration,
                    position,
                    type.nullability(),
                    type.classifier.render(typeParameters),
                )
                .joinToString("\t")
        )
        type.arguments.forEachIndexed { index, projection ->
            val argumentPosition = "$position.typeArgument[$index]"
            val argumentType = projection.type
            if (argumentType == null) {
                add("KOTLIN_PROJECTION\t$declaration\t$argumentPosition\tSTAR")
            } else {
                add("KOTLIN_PROJECTION\t$declaration\t$argumentPosition\t${projection.variance}")
                addType(declaration, argumentPosition, argumentType, typeParameters)
            }
        }
        type.outerType?.let { addType(declaration, "$position.owner", it, typeParameters) }
        type.abbreviatedType?.let {
            addType(declaration, "$position.abbreviated", it, typeParameters)
        }
        type.flexibleTypeUpperBound?.let { flexible ->
            add("KOTLIN_FLEXIBILITY\t$declaration\t$position\t${flexible.typeFlexibilityId}")
            addType(declaration, "$position.flexibleUpperBound", flexible.type, typeParameters)
        }
    }

    private fun KmType.nullability(): String =
        when {
            isDefinitelyNonNull -> "DEFINITELY_NON_NULL"
            isNullable -> "NULLABLE"
            else -> "NON_NULL"
        }

    private fun KmClassifier.render(typeParameters: Map<Int, KmTypeParameter>): String =
        when (this) {
            is KmClassifier.Class -> "CLASS:${name.replace('/', '.')}"
            is KmClassifier.TypeAlias -> "TYPE_ALIAS:${name.replace('/', '.')}"
            is KmClassifier.TypeParameter ->
                "TYPE_PARAMETER:${typeParameters[id]?.name ?: error("Unknown type parameter id $id")}"
        }

    private fun Visibility.isApiVisibility(): Boolean =
        this == Visibility.PUBLIC || this == Visibility.PROTECTED

    private fun isEffectivelyPublicKotlinClass(type: Class<*>): Boolean {
        var current: Class<*>? = type
        while (current != null) {
            val annotation = current.getAnnotation(Metadata::class.java) ?: return false
            val metadata = KotlinClassMetadata.readStrict(annotation)
            if (
                metadata !is KotlinClassMetadata.Class ||
                    !metadata.kmClass.visibility.isApiVisibility()
            ) {
                return false
            }
            current = current.enclosingClass
        }
        return true
    }

    private fun fixtureClasses(packageSegment: String, vararg simpleNames: String): List<Class<*>> =
        simpleNames.map { simpleName ->
            Class.forName(
                "io.github.ulviar.procwright.kotlin.nullability.$packageSegment.$simpleName",
                false,
                KotlinSourceNullabilityCompatibility::class.java.classLoader,
            )
        }

    private fun normalizedFixtureSnapshot(type: Class<*>, packageSegment: String): Set<String> =
        normalizedFixtureSnapshot(listOf(type), packageSegment)

    private fun normalizedFixtureSnapshot(
        types: Collection<Class<*>>,
        packageSegment: String,
    ): Set<String> {
        val dottedPrefix = "io.github.ulviar.procwright.kotlin.nullability.$packageSegment"
        val binaryPrefix = "io/github/ulviar/procwright/kotlin/nullability/$packageSegment"
        return snapshot(types).mapTo(TreeSet()) { line ->
            line.replace(dottedPrefix, "fixture").replace(binaryPrefix, "fixture")
        }
    }

    private fun assertContains(snapshot: Set<String>, fragment: String) {
        check(snapshot.any { it.contains(fragment) }) {
            "Compiled metadata fixture did not exercise '$fragment': $snapshot"
        }
    }

    private fun isParameterNameSignature(signature: String): Boolean =
        signature.startsWith("KOTLIN_PARAMETER_NAME\t")

    private fun parameterNameKey(signature: String): String {
        val fields = signature.split('\t')
        return "${fields[1].substringBefore('(')}|${fields[2]}|${fields[3]}"
    }

    private fun kmType(classifier: KmClassifier): KmType =
        KmType().apply { this.classifier = classifier }

    private fun nullableType(classifier: KmClassifier): KmType =
        kmType(classifier).apply { isNullable = true }

    private fun valueParameter(name: String, type: KmType): KmValueParameter =
        KmValueParameter(name).apply { this.type = type }

    private fun className(root: Path, classFile: Path): String =
        root
            .relativize(classFile)
            .toString()
            .removeSuffix(".class")
            .replace(java.io.File.separatorChar, '.')

    private fun position(signature: String): String = signature.split('\t')[2]

    private fun writeBaseline(path: Path, snapshot: Set<String>) {
        Files.createDirectories(path.parent)
        Files.write(
            path,
            listOf("# Procwright public Kotlin source-nullability baseline", HEADER, "") +
                snapshot.sorted(),
            StandardCharsets.UTF_8,
        )
    }

    private fun verifyBaseline(path: Path, current: Set<String>) {
        check(Files.isRegularFile(path)) { "Kotlin source-nullability baseline is missing: $path" }
        val baseline =
            Files.readAllLines(path, StandardCharsets.UTF_8)
                .map(String::trim)
                .filter { it.isNotEmpty() && !it.startsWith('#') }
                .toSet()
        val diff = compatibilityDiff(baseline, current)
        check(diff.removedOrChanged.isEmpty() && diff.added.isEmpty()) {
            buildString {
                append("Public Kotlin source nullability no longer matches the baseline.")
                appendDiff("Removed or changed signatures", diff.removedOrChanged)
                appendDiff("Added signatures", diff.added)
            }
        }
    }

    private fun compatibilityDiff(baseline: Set<String>, current: Set<String>): CompatibilityDiff =
        CompatibilityDiff(TreeSet(baseline - current), TreeSet(current - baseline))

    private fun StringBuilder.appendDiff(title: String, signatures: Set<String>) {
        if (signatures.isNotEmpty()) {
            appendLine().append(title).append(':')
            signatures.take(80).forEach { appendLine().append("  ").append(it) }
        }
    }

    private data class CompatibilityDiff(val removedOrChanged: Set<String>, val added: Set<String>)
}

internal class KotlinSourceNullabilityCompatibilityTest {

    @Test
    fun `hostile compiled metadata proves every nullability path is compared`() {
        KotlinSourceNullabilityCompatibility.selfTest()
    }
}
